#!/usr/bin/env python3
"""Create a tracking issue in the monitoring repo with CI failure results.

Reads the output JSON from check_nightly_status.py and creates a GitHub issue
with structured failure information.
"""
import os
import sys
import json
import argparse
import requests
from datetime import datetime, timezone

GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")
HEADERS = {
    "Authorization": f"token {GITHUB_TOKEN}",
    "Accept": "application/vnd.github+json",
}
# Where to create tracking issues (your own repo for now)
TRACKING_REPO = os.environ.get("TRACKING_REPO", "ZhaoqiongZ/xpu-ci-monitor")


def format_issue_body(data):
    """Format CI failure data into a GitHub issue body."""
    commit = data.get("commit_sha", "unknown")[:12]
    failures = data.get("failures", [])
    unique_tests = data.get("unique_failed_tests", [])
    
    # Header
    lines = [
        "## XPU CI Nightly Status Report",
        "",
        f"**Date:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        f"**PyTorch Commit:** [`{commit}`](https://github.com/pytorch/pytorch/commit/{data.get('commit_sha', '')})",
        f"**Status:** {'ALL PASS' if data['status'] == 'ALL_PASS' else 'HAS FAILURES'}",
        f"**Failed Jobs:** {len(failures)}",
        f"**Unique Failed Tests:** {len(unique_tests)}",
        "",
        "---",
        "",
    ]

    if not unique_tests:
        lines.append("All XPU tests passed! No action needed.")
        return "\n".join(lines)

    # Summary table
    lines.append("### Failed Tests Summary")
    lines.append("")
    lines.append("| # | Test | File | Shard |")
    lines.append("|---|------|------|-------|")
    for i, test_id in enumerate(unique_tests, 1):
        # Parse test_id: "test/inductor/test_foo.py::TestClass::test_method"
        parts = test_id.split("::")
        test_file = parts[0] if parts else test_id
        test_name = parts[-1] if len(parts) > 1 else ""
        # Find which shard
        shard = "?"
        for f in failures:
            if test_id in f.get("failed_tests", []):
                # Extract shard number from job name
                jn = f["job_name"]
                if "test (default," in jn:
                    shard = jn.split("test (default,")[1].split(",")[0].strip()
                break
        lines.append(f"| {i} | `{test_name}` | `{test_file}` | {shard} |")

    lines.append("")

    # Detailed per-failure info
    lines.append("### Detailed Failures")
    lines.append("")
    for i, test_id in enumerate(unique_tests, 1):
        parts = test_id.split("::")
        test_file = parts[0] if parts else test_id
        test_class = parts[1] if len(parts) > 1 else ""
        test_name = parts[2] if len(parts) > 2 else (parts[1] if len(parts) > 1 else "")

        lines.append(f"#### {i}. `{test_name}`")
        lines.append("")
        lines.append(f"- **Full ID:** `{test_id}`")
        lines.append(f"- **File:** `{test_file}`")
        lines.append(f"- **Class:** `{test_class}`")

        # Find job info
        for f in failures:
            if test_id in f.get("failed_tests", []):
                lines.append(f"- **Job:** [{f['job_name']}]({f['job_url']})")
                break

        lines.append(f"- **Bisect Status:** Pending")
        lines.append(f"- **Fix Status:** Pending")
        lines.append("")

    # Commands section
    lines.extend([
        "---",
        "",
        "### Commands",
        "",
        "| Command | Action |",
        "|---------|--------|",
        "| `/approve` | Submit all fixes as PR(s) to pytorch/pytorch |",
        "| `/approve N` | Submit fix for failure #N only |",
        "| `/revise N <feedback>` | Request changes on failure #N |",
        "| `/rerun N --since YYYY-MM-DD` | Re-bisect failure #N with new params |",
        "| `/skip N` | Mark failure #N for manual handling |",
        "| `/status` | Show current status |",
        "",
        "---",
        f"*Auto-generated by [xpu-ci-monitor](https://github.com/{TRACKING_REPO})*",
    ])

    return "\n".join(lines)


def check_existing_issue(date_str):
    """Check if an issue for today already exists."""
    url = f"https://api.github.com/repos/{TRACKING_REPO}/issues"
    params = {"state": "open", "labels": "ci-nightly", "per_page": 10}
    resp = requests.get(url, headers=HEADERS, params=params)
    if resp.status_code == 200:
        for issue in resp.json():
            if date_str in issue["title"]:
                return issue["number"]
    return None


def create_issue(title, body, labels=None):
    """Create a GitHub issue."""
    url = f"https://api.github.com/repos/{TRACKING_REPO}/issues"
    payload = {"title": title, "body": body, "labels": labels or []}
    resp = requests.post(url, headers=HEADERS, json=payload)
    if resp.status_code == 201:
        issue = resp.json()
        print(f"Issue created: {issue['html_url']}")
        return issue
    else:
        print(f"Failed to create issue: {resp.status_code} {resp.text[:200]}")
        return None


def update_issue(issue_number, body):
    """Update an existing GitHub issue body."""
    url = f"https://api.github.com/repos/{TRACKING_REPO}/issues/{issue_number}"
    payload = {"body": body}
    resp = requests.patch(url, headers=HEADERS, json=payload)
    if resp.status_code == 200:
        print(f"Issue #{issue_number} updated")
        return resp.json()
    else:
        print(f"Failed to update issue: {resp.status_code}")
        return None


def main():
    parser = argparse.ArgumentParser(description="Create tracking issue from CI results")
    parser.add_argument("--input", type=str, required=True, help="Input JSON from check_nightly_status.py")
    parser.add_argument("--dry-run", action="store_true", help="Print issue body without creating")
    args = parser.parse_args()

    if not GITHUB_TOKEN and not args.dry_run:
        print("ERROR: GITHUB_TOKEN not set", file=sys.stderr)
        sys.exit(1)

    with open(args.input) as f:
        data = json.load(f)

    body = format_issue_body(data)
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    commit_short = data.get("commit_sha", "unknown")[:12]
    n_failures = len(data.get("unique_failed_tests", []))

    if data["status"] == "ALL_PASS":
        title = f"[XPU CI] {date_str} - ALL PASS ({commit_short})"
    else:
        title = f"[XPU CI] {date_str} - {n_failures} failure(s) ({commit_short})"

    if args.dry_run:
        print(f"=== TITLE ===\n{title}\n")
        print(f"=== BODY ===\n{body}")
        return

    # Check if today's issue already exists
    existing = check_existing_issue(date_str)
    if existing:
        print(f"Updating existing issue #{existing}")
        update_issue(existing, body)
    else:
        labels = ["ci-nightly"]
        if data["status"] != "ALL_PASS":
            labels.append("has-failures")
        create_issue(title, body, labels)


if __name__ == "__main__":
    main()
